name: Build GBA ROM
on:
  push:
    branches:
      - acceptance

jobs:
  build-rom:
    runs-on: ubuntu-latest
    container: sunbr0/gba_img:7e5b2b37

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove Butano submodule
        run: |
          sudo rm -rf vendor/butano

      - name: Checkout Butano repo
        uses: actions/checkout@v2
        with:
          repository: GValiente/butano
          path: vendor/butano

      - name: Build GBA ROM
        run: |
          make -j$(nproc) VARIANT=RELEASE

      - name: Save ROM as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tap-tap-advance
          path: ./tap-tap-advance.gba